apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-kandidatsok
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.intern.dev.nav.no/rekrutteringsbistand-kandidatsok
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-kandidatsok/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-kandidatsok/internal/isReady
