name: Bygg og deploy

on: [push]

env:
    BUNDLE: ${{ github.sha }}

jobs:
    bygg-applikasjon:
        name: Bygg applikasjon
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
            - name: Installer avhengigheter
              run: npm ci
            - name: Bygg applikasjon
              run: npm run build
            - name: Lagre bundle
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.IMAGE }}
                  path: bundle
                  retention-days: 7

    last-opp-dev:
        name: Last opp til cdn i dev
        runs-on: ubuntu-latest
        needs: bygg-applikasjon
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fjern-kandidatmatch'

        steps:
            - name: Hent bundle
              uses: actions/download-artifact@v2
              with:
                  name: ${{ env.IMAGE }}
                  path: bundle

            - id: upload
              uses: navikt/frontend/actions/cdn-upload/v1@main
              with:
                  cdn-team-name: toii
                  source: ./some/file.ext
                  destination: '/rekrutteringsbistand-kandidatsok/dev/'

    last-opp-prod:
        name: Last opp til cdn i dev
        runs-on: ubuntu-latest
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Hent bundle
              uses: actions/download-artifact@v2
              with:
                  name: ${{ env.IMAGE }}
                  path: bundle

            - id: upload
              uses: navikt/frontend/actions/cdn-upload/v1@main
              with:
                  cdn-team-name: toii
                  source: ./some/file.ext
                  destination: '/rekrutteringsbistand-kandidatsok/dev/'
